### ISSUE TITLE
The route for the 'home' is defined twice

### ISSUE THREAD

**Issue by AryanGupta0007** [neelansh27/cgpa-calc#1]
The route for home is defined twice like this:
@app.route("/home")
def home():
    return render_template('home.html')

@app.route("/home",methods=['POST'])
def submission():
    marks=request.form.getlist('marks',type=int)
    credits=request.form.getlist('credits',type=int)
    cgpa=0
    for i in range(len(marks)):
        if marks[i]>=90 and marks[i]<=100:
            cgpa+=10*credits[i]
        elif marks[i]>=75 and marks[i]<=89:
            cgpa+=9*credits[i]
        elif marks[i]>=65 and marks[i]<=74:
            cgpa+=8*credits[i]
        elif marks[i]>=55 and marks[i]<=64:
            cgpa+=7*credits[i]
        elif marks[i]>=50 and marks[i]<=54:
            cgpa+=6*credits[i]
        elif marks[i]>=45 and marks[i]<=49:
            cgpa+=5*credits[i]
        elif marks[i]>=40 and marks[i]<=44:
            cgpa+=4*credits[i]
    cgpa/=sum(credits)
    return redirect(url_for('cgpa',cgpa=cgpa))

but it can be integrated into one which will be more readable and look better.

**Comment by neelansh27** [comment]
One home route is for GET request and the other one is for POST request and therefore it leads to no actual problems or any unexpected behaviour. Readability is a matter of personal preference and I found it easier to interpret this way.

Thanks for taking your time and review my code.
